sonar.projectKey=VidiomTM_svelteuml
sonar.organization=VidiomTM

sonar.sources=src
sonar.tests=tests
sonar.exclusions=tests/fixtures/**,tests/**/*.snap
sonar.cpd.exclusions=**/tests/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
