@startuml Package Diagram

top to bottom direction

package "lib" as lib {
  class "Button" <<component>>
  class "clearUser" <<function>> <<Exported>>
  class "setUser" <<function>> <<Exported>>
  class "userStore" <<store>>
}

package "routes" as routes {
  class "+layout" <<component>>
  class "+layout" <<layout>>
  class "+page" <<component>>
  class "+page" <<component>>
  class "+page" <<page>>
  class "+page" <<page>>
  class "+server" <<endpoint>>
  class "GET" <<function>> <<Exported>>
  class "load" <<function>> <<Exported>>
  class "load" <<function>> <<Exported>>
  class "POST" <<function>> <<Exported>>
}

routes ..> lib : 1

@enduml