#!/usr/bin/env bash
set -euo pipefail

SNAPSHOT_GLOB="tests/**/__snapshots__/*.snap"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "::group::Save current snapshots" >&2
for f in $SNAPSHOT_GLOB; do
  mkdir -p "$TMPDIR/$(dirname "$f")"
  cp "$f" "$TMPDIR/$f"
done
echo "::endgroup::" >&2

echo "::group::Update snapshots" >&2
pnpm vitest run --update 2>&1 || true
echo "::endgroup::" >&2

echo "::group::Diff snapshots" >&2
diff_body=""
found=false

for f in $SNAPSHOT_GLOB; do
  if [ ! -f "$TMPDIR/$f" ]; then
    found=true
    diff_body+="### 📸 New: \`$f\`
\`\`\`plantuml
$(cat "$f")
\`\`\`

"
    echo "  ▶ New: $f" >&2
    continue
  fi
  d=$(diff "$TMPDIR/$f" "$f" || true)
  if [ -n "$d" ]; then
    found=true
    diff_body+="### 📸 Changed: \`$f\`
\`\`\`diff
$d
\`\`\`

"
    echo "  ▶ Changed: $f" >&2
  fi
done
echo "::endgroup::" >&2

if [ "$found" = false ]; then
  echo "No snapshot differences." >&2
  exit 0
fi

sha=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
cat <<EOF
## Snapshot Diff Report

${diff_body}<sup>Generated by snapshot-diff CI on \`${sha}\`</sup>
EOF
