import { basename } from "node:path";

/**
 * E2.6 — Skip rules: $types, generated files, node_modules.
 *
 * Centralises all "should we skip this file?" logic so every extractor can
 * call a single function rather than duplicating path guards.
 */

/** Patterns that mark a file as auto-generated or noise. */
const GENERATED_BASENAME_PATTERNS: RegExp[] = [/^__types__\.d\.ts$/, /\.d\.ts$/];

/** Fragments that must NOT appear anywhere in the absolute path. */
const SKIP_PATH_FRAGMENTS: string[] = [
	"node_modules",
	"/.svelte-kit/",
	"/dist/",
	"/.git/",
	"/$types",
	"/__types__",
];

/**
 * Returns `true` if the file at `filePath` should be silently skipped by all
 * symbol extractors.
 *
 * Skipped categories:
 * - `.d.ts` declaration files (including `__types__.d.ts` generated by SvelteKit)
 * - Anything inside `node_modules`, `.svelte-kit`, `dist`, `.git`
 * - SvelteKit internal `$types` / `__types__` virtual modules
 */
export function shouldSkipFile(filePath: string): boolean {
	// Check path fragments first (cheapest rejection)
	for (const fragment of SKIP_PATH_FRAGMENTS) {
		if (filePath.includes(fragment)) {
			return true;
		}
	}

	// Check the basename for generated file patterns
	const name = basename(filePath);
	for (const pattern of GENERATED_BASENAME_PATTERNS) {
		if (pattern.test(name)) {
			return true;
		}
	}

	return false;
}

/**
 * Returns `true` if `specifier` is a virtual/internal SvelteKit alias that
 * should not be treated as a real file reference.
 *
 * Examples: `$types`, `$app/stores`, `$env/static/public`, `__sveltekit_...`
 */
export function isVirtualSpecifier(specifier: string): boolean {
	return (
		specifier.startsWith("$types") ||
		specifier.startsWith("$app/") ||
		specifier.startsWith("$env/") ||
		specifier.startsWith("__sveltekit")
	);
}
